### ISSUE TITLE
expired access/refresh token

### ISSUE THREAD

**Issue by jsweeney0530** [xgeek-net/salesforce-mass-editor#4]
──────────────────────────────────────────────
[2018-01-23 15:15] SESSION , {"orgId":"ENCRYPTED","userName":"ENCRYPTED","userId":"ENCRYPTED","salesforceURL":"https://cssny--Staging.cs92.my.salesforce.com","language":"en_US","dateFormat":"M/d/yyyy","dateTimeFormat":"M/d/yyyy h:mm a"}
[2018-01-23 15:15] INIT , ICAN_Deliverable__c , 00B3F000000V1UkUAK
[2018-01-23 15:15] CHECK TOKEN , true
[2018-01-23 15:15] CHECK METADATA , true
[2018-01-23 15:15] [ERROR] invalid_grant: expired access/refresh token
    at chrome-extension://mnmlmkmjjhpbfemhmhpcpfkdlgadbigf/dist/js/main.min.js:11:11957
    at o (chrome-extension://mnmlmkmjjhpbfemhmhpcpfkdlgadbigf/dist/js/main.min.js:16:19988)
    at chrome-extension://mnmlmkmjjhpbfemhmhpcpfkdlgadbigf/dist/js/main.min.js:16:20731
    at MutationObserver.r (chrome-extension://mnmlmkmjjhpbfemhmhpcpfkdlgadbigf/dist/js/main.min.js:12:7777)

**Comment by xgeek-net** [comment]
@jsweeney0530 Did it work after you refresh list page?

**Comment by xgeek-net** [comment]
Hi, @jsweeney0530 
This issue is fixed in latest version(v3.1.0), please update it and try again.
