### ISSUE TITLE
The requested resource does not exist

### ISSUE THREAD

**Issue by GDickens3** [xgeek-net/salesforce-mass-editor#42]
`You can also send the following log data to admin@xgeek.net, if you don't wanna public any information on Github`
──────────────────────────────────────────────
[2019-09-25 08:47] SESSION , {"orgId":"ENCRYPTED","sessionId":"ENCRYPTED","userName":"ENCRYPTED","userId":"ENCRYPTED","salesforceURL":"https://na66.salesforce.com","language":"en_US","dateFormat":"M/d/yyyy","dateTimeFormat":"M/d/yyyy h:mm a"}
[2019-09-25 08:47] INIT , a4W
[2019-09-25 08:47] CHECK TOKEN , true
[2019-09-25 08:47] CHECK METADATA , true
[2019-09-25 08:47] VALIDATE , {"activateable":false,"createable":true,"custom":true,"customSetting":false,"deletable":true,"deprecatedAndHidden":false,"feedEnabled":false,"hasSubtypes":false,"isSubtype":false,"keyPrefix":"a4W","label":"Account Takeover","labelPlural":"Account Takeover","layoutable":true,"mergeable":false,"mruEnabled":true,"name":"Account_Takeover__c","queryable":true,"replicateable":true,"retrieveable":true,"searchable":true,"triggerable":true,"undeletable":true,"updateable":true,"urls":{"approvalLayouts":"/services/data/v39.0/sobjects/Account_Takeover__c/describe/approvalLayouts","compactLayouts":"/services/data/v39.0/sobjects/Account_Takeover__c/describe/compactLayouts","defaultValues":"/services/data/v39.0/sobjects/Account_Takeover__c/defaultValues?recordTypeId&fields","describe":"/services/data/v39.0/sobjects/Account_Takeover__c/describe","layouts":"/services/data/v39.0/sobjects/Account_Takeover__c/describe/layouts","quickActions":"/services/data/v39.0/sobjects/Account_Takeover__c/quickActions","rowTemplate":"/services/data/v39.0/sobjects/Account_Takeover__c/{ID}","sobject":"/services/data/v39.0/sobjects/Account_Takeover__c"}}
[2019-09-25 08:50] DESCRIBE ERROR , {"name":"NOT_FOUND","errorCode":"NOT_FOUND"}
[2019-09-25 08:50] [ERROR] NOT_FOUND: The requested resource does not exist
    at d.getError (chrome-extension://mnmlmkmjjhpbfemhmhpcpfkdlgadbigf/dist/js/main.min.js:10:4969)
    at chrome-extension://mnmlmkmjjhpbfemhmhpcpfkdlgadbigf/dist/js/main.min.js:10:3319
    at o (chrome-extension://mnmlmkmjjhpbfemhmhpcpfkdlgadbigf/dist/js/main.min.js:15:16611)
    at chrome-extension://mnmlmkmjjhpbfemhmhpcpfkdlgadbigf/dist/js/main.min.js:15:17354
    at MutationObserver.r (chrome-extension://mnmlmkmjjhpbfemhmhpcpfkdlgadbigf/dist/js/main.min.js:11:4368)

**Comment by GDickens3** [comment]
Removed and re-added the extension solved issue.
