### ISSUE TITLE
The requested resource does not exist

### ISSUE THREAD

**Issue by MitsuakiSugimura** [xgeek-net/salesforce-mass-editor#5]
`You can also send the following log data to admin@xgeek.net, if you don't wanna public any information on Github`
──────────────────────────────────────────────
[2018-01-25 11:56] SESSION , {"orgId":"ENCRYPTED","userName":"ENCRYPTED","userId":"ENCRYPTED","salesforceURL":"https://org62.my.salesforce.com","language":"en_US","dateFormat":"yyyy/MM/dd","dateTimeFormat":"yyyy/MM/dd H:mm"}
[2018-01-25 11:56] INIT , Travel_Approval__c , Recent
[2018-01-25 11:56] CHECK TOKEN , false
[2018-01-25 11:56] CHECK METADATA , true
[2018-01-25 11:56] [ERROR] NOT_FOUND: The requested resource does not exist
    at d.getError (chrome-extension://mnmlmkmjjhpbfemhmhpcpfkdlgadbigf/dist/js/main.min.js:11:8385)
    at chrome-extension://mnmlmkmjjhpbfemhmhpcpfkdlgadbigf/dist/js/main.min.js:11:6735
    at o (chrome-extension://mnmlmkmjjhpbfemhmhpcpfkdlgadbigf/dist/js/main.min.js:16:19988)
    at chrome-extension://mnmlmkmjjhpbfemhmhpcpfkdlgadbigf/dist/js/main.min.js:16:20731
    at MutationObserver.r (chrome-extension://mnmlmkmjjhpbfemhmhpcpfkdlgadbigf/dist/js/main.min.js:12:7777)

**Comment by xgeek-net** [comment]
@MitsuakiSugimura 
Does it work on your other salesforce org? etc Sandbox..
