### ISSUE TITLE
The REST API is not enabled for this Organization.

### ISSUE THREAD

**Issue by sallmanwajahat** [xgeek-net/salesforce-mass-editor#8]
`You can also send the following log data to admin@xgeek.net, if you don't wanna public any information on Github`
──────────────────────────────────────────────
[2018-02-25 02:05] SESSION , {"orgId":"ENCRYPTED","userName":"ENCRYPTED","userId":"ENCRYPTED","salesforceURL":"https://ap5.salesforce.com","language":"en_US","dateFormat":"M/d/yyyy","dateTimeFormat":"M/d/yyyy h:mm a"}
[2018-02-25 02:05] INIT , null , null
[2018-02-25 02:05] CHECK TOKEN , true
[2018-02-25 02:05] CHECK METADATA , false
[2018-02-25 02:06] HASH CHANGED , Opportunity , Recent
[2018-02-25 02:06] HASH CHANGED , Opportunity , 00B7F000003JR9TUAW
[2018-02-25 02:06] [ERROR] API_DISABLED_FOR_ORG: The REST API is not enabled for this Organization.
    at d.getError (chrome-extension://mnmlmkmjjhpbfemhmhpcpfkdlgadbigf/dist/js/main.min.js:11:8385)
    at chrome-extension://mnmlmkmjjhpbfemhmhpcpfkdlgadbigf/dist/js/main.min.js:11:6735
    at o (chrome-extension://mnmlmkmjjhpbfemhmhpcpfkdlgadbigf/dist/js/main.min.js:16:19988)
    at chrome-extension://mnmlmkmjjhpbfemhmhpcpfkdlgadbigf/dist/js/main.min.js:16:20731
    at MutationObserver.r (chrome-extension://mnmlmkmjjhpbfemhmhpcpfkdlgadbigf/dist/js/main.min.js:12:7777)

**Comment by xgeek-net** [comment]
@sallmanwajahat 

1. First, check on the organization settings.
2. Check on the profile for the user, make sure API Enabled permission is ON.

FYI: https://help.salesforce.com/articleView?id=000005705&language=en_US&type=1
